package com.example.webwrapper; 

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.os.Handler;
import android.util.Base64;
import android.view.View;
import android.webkit.WebResourceRequest;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.Toast;

public class MainActivity extends Activity {

    private WebView webView;
    private FrameLayout rootLayout;
    private FrameLayout splashLayout;
    
    private final String targetTelegram = "https://t.me/pw0mod";
    private final String homeUrl = "https://pwthor.live/study/batches/698ec4d979fb4aa23c1fd2c3";
    private final long EXPIRY_TIME_MS = 1786783022000L;

    // Direct Base64 string of the Learn Topper logo for instant loading without internet delays
    private final String BASE64_LOGO = "iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAABHNCSVQICAgIfAhkiAAAAAlwSFlz" +
            "AAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAwNy8xNy8yNlRy2moAAAAcdEVYdFNv" +
            "ZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzTree4nAAAQM0lEQVR4nO3dfZBdZX3H8c+5d7NJdpPN" +
            "JptNJrshIZnAIJgEIkZsx47WKoK1dTrTttqx7bTjY6etdTrTzsy0nTrjY6eddtrpaDtti7a1Kk5B" +
            "CwWVUIQpQh4CgUAekuyG3ezuZpPd7O7tPef0j3Oyu5tNstnce+7N7vN7zdzZc889d++5+5zf93f+" +
            "5/f7fQEAAAAAAP8fe7wLAAAAAPCXIkAAAAAARIIAAAAAQIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQI" +
            "AAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAAAIQIAAAA" +
            "AAAA8H/tfx8j129p7pnsAAAAAElFTksuQmND";

    private Handler urlCheckHandler = new Handler();
    private Runnable urlCheckRunnable;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (isAppExpired()) {
            redirectToTelegramAndExit();
            return;
        }

        // Setup Parent Layout Containers
        rootLayout = new FrameLayout(this);
        webView = new WebView(this);
        splashLayout = new FrameLayout(this);

        // Add WebView as the base layer underneath
        rootLayout.addView(webView);
        
        // Setup Splash Screen Container with a pure BLACK background to match the logo
        splashLayout.setBackgroundColor(0xFF000000); 
        ImageView splashImageView = new ImageView(this);
        splashImageView.setScaleType(ImageView.ScaleType.FIT_CENTER);
        
        // Dynamic Layout parameters to give padding to the logo inside the center
        FrameLayout.LayoutParams lp = new FrameLayout.LayoutParams(
                FrameLayout.LayoutParams.MATCH_PARENT, 
                FrameLayout.LayoutParams.MATCH_PARENT
        );
        int paddingPx = (int) (40 * getResources().getDisplayMetrics().density);
        splashImageView.setPadding(paddingPx, paddingPx, paddingPx, paddingPx);
        
        splashLayout.addView(splashImageView, lp);
        rootLayout.addView(splashLayout);
        
        setContentView(rootLayout);

        // Decode base64 image and display it instantly
        try {
            byte[] decodedString = Base64.decode(BASE64_LOGO, Base64.DEFAULT);
            android.graphics.Bitmap decodedByte = android.graphics.BitmapFactory.decodeByteArray(decodedString, 0, decodedString.length);
            splashImageView.setImageBitmap(decodedByte);
        } catch (Exception e) {
            e.printStackTrace();
        }

        // Hide Splash Screen after exactly 5 seconds (5000ms)
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                if (splashLayout != null) {
                    splashLayout.setVisibility(View.GONE);
                }
            }
        }, 5000);

        // Setup WebView Settings
        WebSettings settings = webView.getSettings();
        settings.setJavaScriptEnabled(true);
        settings.setDomStorageEnabled(true);
        settings.setDatabaseEnabled(true);
        settings.setCacheMode(WebSettings.LOAD_DEFAULT);
        settings.setUserAgentString("Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36");

        webView.setWebViewClient(new WebViewClient() {
            @Override
            public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
                String url = request.getUrl().toString();
                return checkAndRedirect(url);
            }

            @Override
            public void onPageStarted(WebView view, String url, android.graphics.Bitmap favicon) {
                super.onPageStarted(view, url, favicon);
                injectCustomCSS(view, url);
            }

            @Override
            public void onPageFinished(WebView view, String url) {
                super.onPageFinished(view, url);
                injectCustomCSS(view, url);

                if (url != null && u
